name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install Python 3.14
        run: uv python install 3.14
      - name: Test import
        run: |
          uv run --python 3.14 --with-editable '.' python -c 'import globalwarmingpotentials; print(f"globalwarmingpotentials {globalwarmingpotentials.__version__}")'

  deploy-pypi:
    needs: test
    if: startsWith(github.event.ref, 'refs/tags/v')
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish

  deploy-npm:
    needs: test
    if: startsWith(github.event.ref, 'refs/tags/v')
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - run: npm run build --if-present
      - run: npm publish
